# Generated by Django 3.0.5 on 2020-04-01 23:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shop.assist


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('Saltwater_fish', 'ماهی آب شور'), ('Freshwater_fish', 'ماهی آب شیرین'), ('supplies', 'وسایل و تجهیزات'), ('reef', 'ریف')], max_length=30)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='shop/image_product')),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('orginal_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('rate', shop.assist.IntegerRangeField(blank=True)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('has_offer', models.BooleanField()),
                ('exist', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('addres', models.CharField(max_length=150)),
                ('telegram_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('open_time', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ShopNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_number', to='shop.Shop')),
            ],
        ),
    ]
